#!/usr/bin/env bash
#Install nginx on your web-01
sudo apt-get -y update
sudo apt-get -y install nginx
sudo ufw allow "Nginx HTTP"
echo 'Hello World!' | sudo tee /var/www/html/index.html > /dev/null
config_old="location \/ { try_files uri uri\/ =404; }"
config_new="location \/redirect_me { return 301 http:\/\/httpforever.com\/; }"
sudo sed -i -s "s/${config_old}/${config_new}/" /etc/nginx/sites-enabled/default
sudo service nginx restart
