#!/usr/bin/env bash

# Check if the configuration is already applied on both servers
if ! grep -q "server 526434-web-01 34.204.82.115:80 check" /etc/haproxy/haproxy.cfg || ! grep -q "server 526434-web-02 3.83.227.236:80 check" /etc/haproxy/haproxy.cfg; then
    # Install and configure HAProxy on your lb-01 server
    apt-get -y install --no-install-recommends software-properties-common
    add-apt-repository ppa:vbernat/haproxy-2.6
    apt-get install haproxy=2.6.*

    # Configure HAProxy to send traffic to web-01 and web-02
    echo '
    frontend http_front
        bind *:80
        default_backend http_back
        timeout client 30s

    backend http_back
        balance roundrobin
        server 526434-web-01 34.204.82.115:80 check
        server 526434-web-02 3.83.227.236:80 check
        timeout server 30s
        timeout connect 5s
    ' >> /etc/haproxy/haproxy.cfg

    # Restart HAProxy
    sudo systemctl restart haproxy
fi
