#!/usr/bin/env bash
# Check if the configuration is already applied on both servers
sudo apt-get -y update
apt-get -y install haproxy

# Configure HAProxy to send traffic to web-01 and web-02
TEMP_CONFIG="/tmp/new_haproxy_config"
cat << EOF > $TEMP_CONFIG
frontend http_front
    bind *:80
    default_backend http_back
    timeout client 30s

backend http_back
    balance roundrobin
    server 526434-web-01 34.204.82.115:80 check
    server 526434-web-02 3.83.227.236:80 check
    timeout server 30s
    timeout connect 5s
EOF
sudo cp /etc/haproxy/haproxy.cfg /etc/haproxy/haproxy.cfg.bak
sudo mv $TEMP_CONFIG /etc/haproxy/haproxy.cfg
sudo systemctl enable haproxy
sudo systemctl restart haproxy
